set INCLUDES= -I../RSDKv5/ -I../dependencies/all/ -I../dependencies/all/tinyxml2/ -I../dependencies/all/iniparser/ 	-I../dependencies/windows/libs_x64/include -I. -I./Objects/

set LINK_PATHS= -L../dependencies/windows/libs_x64/lib

set FLAGS= -static -static-libgcc -static-libstdc++ -g3  -fsigned-char -std=c++17 -fsigned-char -fpermissive -mwindows  -Wl,-Bstatic,--whole-archive -lwinpthread -Wl,--no-whole-archive -ltheora -logg -ld3d9 -lxinput -lcomctl32 -lgdi32 -lwinmm -lole32 -lxaudio2_8 -ld3dcompiler -lksuser

set DEFINES= -DRSDK_USE_DX9=1 -DRETRO_STANDALONE=1 -DRETRO_REVISION=3 -DSONICMANIA_EXPORTS -D_WINDOWS -DWIN32

gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Game.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/AIZEggRobo.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/AIZEncoreTutorial.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/AIZKingClaw.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/AIZRockPile.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/AIZSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/AIZTornado.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/AIZTornadoPath.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/Bloominator.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/EncoreIntro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/FernParallax.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/MonkeyDude.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/Rhinobot.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/SchrodingersCapsule.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/AIZ/Sweep.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/All.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/BSS/BSS_Collectable.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/BSS/BSS_Collected.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/BSS/BSS_Horizon.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/BSS/BSS_HUD.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/BSS/BSS_Message.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/BSS/BSS_Palette.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/BSS/BSS_Player.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/BSS/BSS_Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/BGSwitch.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/BreakableWall.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/Button.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/CollapsingPlatform.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/Decoration.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/Eggman.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/FlingRamp.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/ForceSpin.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/ForceUnstick.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/GenericTrigger.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/Palette.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/ParallaxSprite.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/Platform.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/PlatformControl.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/PlatformNode.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/Projectile.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/SpinBooster.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/TilePlatform.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Common/Water.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Continue/ContinuePlayer.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Continue/ContinueSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/AmoebaDroid.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/Ball.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/Bubbler.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/CaterkillerJr.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/ChemBubble.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/ChemicalBall.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/ChemicalPool.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/CPZ1Intro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/CPZ2Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/CPZBoss.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/CPZSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/CPZShutter.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/DNARiser.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/Grabber.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/OneWayDoor.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/Reagent.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/RotatingStair.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/SpeedBooster.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/Spiny.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/Springboard.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/Staircase.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/StickyPlatform.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/Syringe.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/TippingPlatform.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/TransportTube.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/TubeSpring.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/CPZ/TwistedTubes.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Credits/AnimalHBH.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Credits/CreditsSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Credits/EncoreGoodEnd.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Credits/TAEmerald.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Credits/TryAgain.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Credits/TryAgainE.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Cutscene/ChaosEmerald.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Cutscene/CutsceneHBH.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Cutscene/CutsceneRules.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Cutscene/CutsceneSeq.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Cutscene/FXExpandRing.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Cutscene/FXFade.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Cutscene/FXRuby.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Cutscene/FXSpinRay.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Cutscene/FXTrail.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Cutscene/FXWaveRing.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Cutscene/RubyPortal.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/ERZGunner.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/ERZKing.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/ERZMystic.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/ERZOutro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/ERZRider.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/ERZSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/ERZShinobi.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/ERZStart.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/KleptoMobile.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/PhantomEgg.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/PhantomGunner.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/PhantomHand.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/PhantomKing.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/PhantomMissile.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/PhantomMystic.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/PhantomRider.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/PhantomRuby.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/PhantomShield.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/PhantomShinobi.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/PKingAttack.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/ERZ/RingField.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/BigSqueeze.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/Blaster.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/Clucker.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/Crane.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/Cylinder.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/ElectroMagnet.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/FBZ1Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/FBZ2Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/FBZFan.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/FBZMissile.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/FBZSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/FBZSinkTrash.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/FBZStorm.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/FBZTrash.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/FlameSpring.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/FoldingPlatform.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/HangGlider.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/HangPoint.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/Launcher.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/LightBarrier.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/MagPlatform.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/MagSpikeBall.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/Mine.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/Propeller.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/PropellerShaft.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/SpiderMobile.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/SpiralPlatform.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/SwitchDoor.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/Technosqueek.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/TetherBall.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/Tuesday.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/TwistingDoor.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/FBZ/WarpDoor.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/Batbrain.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/Bridge.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/BurningLog.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/BuzzBomber.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/CheckerBall.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/Chopper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/CorkscrewPath.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/Crabmeat.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/DDWrecker.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/DERobot.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/Fireball.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/GHZ2Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/GHZCutsceneK.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/GHZCutsceneST.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/GHZSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/Motobug.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/Newtron.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/SpikeLog.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/Splats.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/WaterfallSound.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/GHZ/ZipLine.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/ActClear.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Animals.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Announcer.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/APICallback.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/BoundsMarker.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Camera.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Competition.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/COverlay.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Debris.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/DebugMode.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/DialogRunner.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Dust.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/EggPrison.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/EncoreRoute.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Explosion.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/GameOver.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/HUD.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/ImageTrail.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/InvincibleStars.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/InvisibleBlock.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/ItemBox.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Localization.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Music.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/NoSwap.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/PauseMenu.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/PlaneSwitch.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Player.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/ReplayRecorder.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Ring.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/SaveGame.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/ScoreBonus.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Shield.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/SignPost.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Soundboard.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/SpecialRing.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/SpeedGate.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Spikes.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Spring.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/StarPost.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/SuperSparkle.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/TimeAttackGate.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/TitleCard.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Global/Zone.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/Blastoid.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/BreakBar.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/Buggernaut.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/ButtonDoor.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/Current.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/DCEvent.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/DiveEggman.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/Fan.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/Gondola.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/HandLauncher.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/HangConveyor.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/HCZ1Intro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/HCZOneWayDoor.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/HCZSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/HCZSpikeBall.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/Jawz.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/Jellygnite.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/LaundroMobile.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/MegaChopper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/Pointdexter.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/PullChain.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/ScrewMobile.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/Spear.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/TurboSpiker.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/TwistingSlide.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/WaterGush.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HCZ/Whirlpool.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/BadnikHelpers.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/ColorHelpers.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/CompetitionSession.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/DrawHelpers.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/GameProgress.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/LogHelpers.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/MathHelpers.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/Options.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/ParticleHelpers.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/PlayerHelpers.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/PlayerProbe.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/ReplayDB.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Helpers/TimeAttackData.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HPZ/Batbot.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HPZ/Redz.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/HPZ/Stegway.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/BuckwildBall.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/DashLift.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/Drillerdroid.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/DrillerdroidO.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/Fireworm.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/Flamethrower.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/HeavyKing.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/HeavyRider.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/HPZEmerald.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/Iwamodoki.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/KingAttack.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/KingClaw.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LavaFall.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LavaGeyser.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZ1Intro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZ1Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZ1Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZ2Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZ3Cutscene.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZ3Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZ3OutroK.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZ3Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZConvControl.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZConvDropper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZConveyor.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZConvItem.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZConvSwitch.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZFireball.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZRockPile.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZSpikeBall.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/LRZSpiral.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/OrbitSpike.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/Rexon.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/RisingLava.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/RockDrill.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/SkyTeleporter.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/SpikeCrusher.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/Stalactite.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/ThoughtBubble.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/Toxomister.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/Turbine.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/TurretSwitch.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/LRZ/WalkerLegs.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/CompetitionMenu.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/DAControl.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/DASetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/DemoMenu.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/E3MenuSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/ExtrasMenu.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/LevelSelect.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/LogoSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/MainMenu.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/ManiaModeMenu.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/MenuParam.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/MenuSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/OptionsMenu.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/ThanksSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/TimeAttackMenu.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIBackground.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIButton.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIButtonLabel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIButtonPrompt.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UICarousel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UICharButton.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIChoice.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIControl.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UICreditsText.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIDialog.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIDiorama.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIHeading.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIInfoLabel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIKeyBinder.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UILeaderboard.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIMedallionPanel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIModeButton.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIOptionPanel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIPicture.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIPopover.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIRankButton.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIReplayCarousel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIResPicker.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UISaveSlot.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIShifter.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UISlider.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UISubHeading.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UITABanner.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UITAZoneModule.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIText.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UITransition.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIUsernamePopup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIVideo.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIVsCharSelector.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIVsResults.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIVsRoundPicker.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIVsScoreboard.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIVsZoneButton.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIWaitSpinner.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIWidgets.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Menu/UIWinSize.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/BladePole.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/BuzzSaw.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/ConveyorBelt.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/ConveyorPlatform.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/ConveyorWheel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/EggPistonsMKII.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/FarPlane.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/Gachapandora.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/MatryoshkaBom.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/MechaBu.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/MMZ2Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/MMZLightning.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/MMZSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/MMZWheel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/Piston.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/PlaneSeeSaw.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/PohBee.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/RPlaneShifter.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/Scarab.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/SizeLaser.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/SpikeCorridor.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MMZ/VanishPlatform.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/Armadiloid.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/BarStool.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/Bumpalo.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/Cactula.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/CollapsingSand.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/DBTower.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/EggLoco.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/Flipper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/GiantPistol.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/Hatterkiller.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/HeavyMystic.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/Honkytonk.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/LightBulb.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/LocoSmoke.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/MSZ1KIntro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/MSZ2Cutscene.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/MSZCutsceneK.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/MSZCutsceneST.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/MSZSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/MSZSpotlight.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/PaintingEyes.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/Pinata.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/Rattlekiller.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/RollerMKII.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/RotatingSpikes.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/SeeSaw.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/SeltzerBottle.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/SeltzerWater.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/SideBarrel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/SwingRope.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/Tornado.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/TornadoPath.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/UberCaterkiller.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/MSZ/Vultron.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/Aquis.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/BallCannon.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/GasPlatform.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/Hatch.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/MegaOctus.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/MeterDroid.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/Octus.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/OOZ1Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/OOZ2Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/OOZFlames.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/OOZSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/PullSwitch.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/PushSpring.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/Smog.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/Sol.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/OOZ/Valve.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Acetone.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Crate.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/DoorTrigger.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Dragonfly.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/FrostThrower.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/HeavyShinobi.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Ice.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/IceBomba.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/IceSpring.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Ink.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/InkWipe.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/JuggleSaw.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Newspaper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/PaperRoller.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/PetalPile.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Press.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/PrintBlock.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/PSZ1Intro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/PSZ1Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/PSZ2Intro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/PSZ2Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/PSZ2Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/PSZDoor.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/PSZEggman.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/PSZLauncher.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Shiversaw.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Shuriken.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Snowflakes.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/SP500.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/SP500MkII.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Turntable.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/WoodChipper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/PGZ/Woodrow.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Pinball/PBL_Bumper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Pinball/PBL_Camera.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Pinball/PBL_Crane.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Pinball/PBL_Flipper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Pinball/PBL_HUD.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Pinball/PBL_Player.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Pinball/PBL_Ring.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Pinball/PBL_Sector.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Pinball/PBL_Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Pinball/PBL_TargetBumper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Puyo/PuyoAI.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Puyo/PuyoAttack.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Puyo/PuyoBean.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Puyo/PuyoGame.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Puyo/PuyoIndicator.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Puyo/PuyoLabel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Puyo/PuyoLevelSelect.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Puyo/PuyoMatch.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Puyo/PuyoScore.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SBZ/Bomb.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SBZ/Caterkiller.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SBZ/Orbinaut.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/CableWarp.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/Canista.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/CircleBumper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/Clapperboard.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/DirectorChair.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/EggJanken.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/EggJankenPart.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/EggTV.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/FilmProjector.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/FilmReel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/Funnel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/GreenScreen.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/HeavyGunner.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/LEDPanel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/Letterboard.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/LottoBall.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/LottoMachine.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/LoveTester.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/MicDrop.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/PathInverter.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/PimPom.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/PopcornKernel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/PopcornMachine.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/RockemSockem.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/ShopWindow.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/Shutterbug.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/SpinSign.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/SPZ1Intro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/SPZ1Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/SPZ2Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/SPZ2Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/Tubinaut.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/TVFlyingBattery.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/TVPole.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/TVVan.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/WeatherMobile.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SPZ/WeatherTV.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/Beanstalk.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/BouncePlant.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/Bungee.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/Constellation.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/Dango.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/EggTower.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/Fireflies.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/Firework.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/FlowerPod.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/GigaMetal.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/HiLoSign.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/Hotaru.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/HotaruHiWatt.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/HotaruMKII.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/JunctionWheel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/Kabasira.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/Kanabun.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/MetalSonic.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/MonarchPlans.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/MSBomb.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/MSFactory.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/MSHologram.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/MSOrb.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/MSPanel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/RTeleporter.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SDashWheel.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SilverSonic.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SparkRail.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SpikeFlail.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SSZ1Intro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SSZ1Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SSZ1Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SSZ2Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SSZ3Cutscene.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SSZEggman.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SSZSpikeBall.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/SSZSpotlight.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/TimePost.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/TimeTravelSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/TTCutscene.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/UncurlPlant.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/SSZ/YoyoPulley.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Summary/Summary.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Summary/SummaryEmerald.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Title/Title3DSprite.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Title/TitleBG.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Title/TitleEggman.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Title/TitleLogo.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Title/TitleSetup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Title/TitleSonic.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/BallHog.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/CrashTest.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/CrimsonEye.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/EscapeCar.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/FlasherMKII.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/GymBar.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/JacobsLadder.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/LargeGear.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/LaunchSpring.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/MagnetSphere.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/MetalArm.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/MonarchBG.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/PopOut.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/SentryBug.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/TeeterTotter.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/TMZ1Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/TMZ1Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/TMZ2Outro.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/TMZ2Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/TMZ3Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/TMZAlert.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/TMZBarrier.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/TMZCable.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/TMZFlames.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/TurboTurtle.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/TMZ/WallBumper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/SpecialClear.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Camera.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Circuit.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Decoration.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Dust.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_HUD.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_ItemBox.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Message.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Plasma.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Player.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Ring.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Setup.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Shadow.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_SpeedLines.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Sphere.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Springboard.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/UFO/UFO_Water.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Unused/Pendulum.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Unused/SpearBlock.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Unused/TargetBumper.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Unused/WallCrawl.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c Objects/Unused/Wisp.c
gcc %DEFINES% %INCLUDES% %LINK_PATHS% %FLAGS% -c PublicFunctions.c